import { useState, useEffect } from 'react';
import type { ReactNode } from 'react';
import { LanguageContext, type Language, type LanguageContextType } from './languageContext';

// النصوص المترجمة
const translations: Record<Language, Record<string, string>> = {
  ar: {
    // نصوص الصفحة الرئيسية
    'dashboard': 'لوحة التحكم',
    'welcome': 'أهلاً وسهلاً',
    'home': 'الرئيسية',
    
    // نصوص التنقل
    'countries': 'البلدان',
    'cities': 'المدن',
    'areas': 'المناطق',
    'features': 'الميزات',
    'appliances': 'الأجهزة والأدوات',
    'blocks': 'البلوكات',
    'designs': 'التصاميم',
    'logout': 'تسجيل الخروج',
    
    // نصوص تسجيل الدخول
    'login': 'تسجيل الدخول',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'login_button': 'دخول',
    'login_title': 'تسجيل الدخول',
    'login_subtitle': 'أدخل بياناتك للوصول إلى نظام إدارة العقارات',
    'email_placeholder': 'أدخل بريدك الإلكتروني',
    'password_placeholder': 'أدخل كلمة المرور',
    'remember_me': 'تذكرني',
    'forgot_password': 'نسيت كلمة المرور؟',
    'login_error': 'خطأ في البريد الإلكتروني أو كلمة المرور',
    'hide_password': 'إخفاء كلمة المرور',
    'show_password': 'إظهار كلمة المرور',
    'no_account': 'ليس لديك حساب؟',
    'sign_up': 'إنشاء حساب',
    
    // نصوص الإحصائيات
    'total_countries': 'إجمالي البلدان',
    'total_cities': 'إجمالي المدن',
    'total_areas': 'إجمالي المناطق',
    'total_towers': 'إجمالي الأبراج',
    
    // نصوص إدارة البيانات
    'manage_countries': 'إدارة البلدان في النظام',
    'manage_cities': 'إدارة المدن',
    'manage_areas': 'إدارة المناطق',
    'manage_features': 'إدارة ميزات الأبراج',
    'manage_appliances': 'إدارة الأجهزة والأدوات',
    'add_new_country': 'إضافة دولة جديدة',
    'add_new_city': 'إضافة مدينة جديدة',
    'add_new_area': 'إضافة منطقة جديدة',
    'add_new_feature': 'إضافة ميزة جديدة',
    'add_new_appliance': 'إضافة جهاز جديد',
    'edit_country': 'تعديل الدولة',
    'edit_city': 'تعديل المدينة',
    'edit_area': 'تعديل المنطقة',
    'edit_feature': 'تعديل الميزة',
    'edit_appliance': 'تعديل الجهاز',
    
    // نصوص النماذج
    'arabic_name': 'الاسم بالعربية',
    'english_name': 'الاسم بالإنجليزية',
    'enter_arabic_name': 'أدخل الاسم بالعربية',
    'enter_block_code': 'أدخل كود البلوك',
    'enter_english_name': 'أدخل الاسم بالإنجليزية',
    'enter_arabic_description': 'أدخل الوصف بالعربية',
    'enter_english_description': 'أدخل الوصف بالإنجليزية',
    'name': 'الاسم',
    'country_code': 'رمز الدولة',
    'description_ar': 'الوصف بالعربية',
    'description_en': 'الوصف بالإنجليزية',
    'is_active': 'نشط',
    'status': 'الحالة',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'actions': 'الإجراءات',
    'description': 'الوصف',
    
    // نصوص التأكيد
    'confirm_delete': 'تأكيد الحذف',
    'confirm_delete_country': 'هل أنت متأكد من حذف هذه الدولة؟ سيتم حذف جميع المدن والمناطق المرتبطة بها.',
    'confirm_delete_city': 'هل أنت متأكد من حذف هذه المدينة؟ سيتم حذف جميع المناطق المرتبطة بها.',
    'confirm_delete_area': 'هل أنت متأكد من حذف هذه المنطقة؟',
    'confirm_delete_feature': 'هل أنت متأكد من حذف هذه الميزة؟',
    'confirm_delete_appliance': 'هل أنت متأكد من حذف هذا الجهاز؟',
    
    // رسائل النجاح
    'country_added': 'تم إضافة الدولة بنجاح',
    'country_updated': 'تم تحديث الدولة بنجاح',
    'country_deleted': 'تم حذف الدولة بنجاح',
    'city_added': 'تم إضافة المدينة بنجاح',
    'city_updated': 'تم تحديث المدينة بنجاح',
    'city_deleted': 'تم حذف المدينة بنجاح',
    'area_added': 'تم إضافة المنطقة بنجاح',
    'area_updated': 'تم تحديث المنطقة بنجاح',
    'area_deleted': 'تم حذف المنطقة بنجاح',
    'feature_added': 'تم إضافة الميزة بنجاح',
    'feature_updated': 'تم تحديث الميزة بنجاح',
    'feature_deleted': 'تم حذف الميزة بنجاح',
    'appliance_added': 'تم إضافة الجهاز بنجاح',
    'appliance_updated': 'تم تحديث الجهاز بنجاح',
    'appliance_deleted': 'تم حذف الجهاز بنجاح',
    
    // نصوص عامة
    'loading': 'جاري التحميل...',
    'error': 'حدث خطأ',
    'success': 'تم بنجاح',
    'cancel': 'إلغاء',
    'save': 'حفظ',
    'save_changes': 'حفظ التغييرات',
    'delete': 'حذف',
    'edit': 'تعديل',
    'add': 'إضافة',
    'search': 'بحث',
    'close': 'إغلاق',
    'confirm': 'تأكيد',
    'yes': 'نعم',
    'no': 'لا',
    'back': 'رجوع',
  'warning': 'تحذير',
  'note': 'ملاحظة',
    'select_city': 'اختر مدينة لعرض المناطق',
    'click_city': 'انقر على أي مدينة أعلاه لعرض المناطق المتاحة بها',
    
    // رسائل النظام
    'no_data': 'لا توجد بيانات',
    'no_areas_in_city': 'لا توجد مناطق في هذه المدينة',
    'no_features': 'لا توجد ميزات',
    'no_appliances': 'لا توجد أجهزة',
    'network_error': 'خطأ في الشبكة',
    'server_error': 'خطأ في الخادم',
    'unauthorized': 'غير مصرح',
    'forbidden': 'ممنوع',
    'not_found': 'غير موجود',
    'delete_not_supported': 'عملية الحذف غير مدعومة حاليًا',
    'delete_error': 'تعذر الحذف',
    
    // إدارة الميزات - مفاتيح إضافية
    'features_management': 'إدارة ميزات الأبراج',
    'features_management_description': 'إضافة وتعديل وحذف ميزات الأبراج',
    'delete_feature_confirmation': 'هل أنت متأكد من حذف هذه الميزة؟',
    'no_features_description': 'لم يتم إنشاء أي ميزات بعد. ابدأ بإضافة ميزة جديدة.',
    'loading_features': 'جارٍ تحميل الميزات...',
    'feature_active': 'الميزة نشطة',
    'feature_active_description': 'هل هذه الميزة متاحة للاستخدام؟',
    'display_order': 'ترتيب العرض',
    'english_description': 'الوصف بالإنجليزية',
    'arabic_description': 'الوصف بالعربية',
    
    // إدارة التصاميم
    'unitDesigns': 'تصاميم الوحدات',
    'manageUnitDesigns': 'إدارة تصاميم الوحدات بعمليات CRUD شاملة ووظيفة النسخ',
    'addNew': 'إضافة جديد',
    'searchDesigns': 'البحث عن التصاميم...',
    'allCategories': 'جميع الفئات',
    'standard': 'قياسي',
    'luxury': 'فاخر',
    'premium': 'ممتاز',
    'economic': 'اقتصادي',
    'totalDesigns': 'إجمالي التصاميم',
    'sqm': 'م²',
    'copy': 'نسخ',
    'designCategory': 'فئة التصميم',
    'area': 'المساحة',
    'price': 'السعر',
    'noDesigns': 'لا توجد تصاميم وحدات',
    'noDesignsMessage': 'ابدأ بإنشاء تصميم وحدة جديد.',
    'createFirstDesign': 'إنشاء أول تصميم',
    'addNewDesign': 'إضافة تصميم جديد',
    'arabicName': 'الاسم بالعربية',
    'englishName': 'الاسم بالإنجليزية',
    'arabicDescription': 'الوصف بالعربية',
    'englishDescription': 'الوصف بالإنجليزية',
    'pricePerMeter': 'السعر للمتر',
    'targetMarket': 'السوق المستهدف',
    'images': 'الصور',
    'videos': 'الفيديوهات',
    'editDesign': 'تعديل التصميم',
    'copyDesign': 'نسخ التصميم',
    'deleteDesign': 'حذف التصميم',
    'deleteDesignConfirm': 'هل أنت متأكد من حذف هذا التصميم؟ لا يمكن التراجع عن هذا الإجراء.',
    'errorLoadingData': 'خطأ في تحميل البيانات',
    'designDetails': 'تفاصيل التصميم',
    'basicInfo': 'المعلومات الأساسية',
    'bedrooms': 'غرف النوم',
    'bathrooms': 'دورات المياه',
    'livingRooms': 'غرف المعيشة',
    'kitchens': 'المطابخ',
    'balconies': 'الشرفات',
    'priceInfo': 'معلومات السعر',
    'originalPrice': 'السعر الأصلي',
    'discount': 'الخصم',
    'finalPrice': 'السعر النهائي',
    'currency': 'درهم',
    'paymentPlans': 'خطط الدفع',
    'downPayment': 'الدفعة المقدمة',
    'installment': 'القسط',
    'months': 'أشهر',
    'maintenanceInfo': 'معلومات الصيانة',
    'gasInfo': 'معلومات الغاز',
    'additionalExpenses': 'المصاريف الإضافية',
    'officeCommission': 'عمولة المكتب',
    'municipalityFees': 'رسوم البلدية',
    'electricityFees': 'رسوم الكهرباء',
    'proFees': 'الرسوم الاحترافية',
    'insuranceAmount': 'قيمة التأمين',
    'maintenanceAmount': 'مبلغ الصيانة',
    'maintenanceType': 'نوع الصيانة',
    'gasType': 'نوع الغاز',
    'videoGallery': 'معرض الفيديو',
    'imageGallery': 'معرض الصور',
    'freePeriod': 'الفترة المجانية',
    'days': 'أيام',
    'quantity': 'الكمية',
    
    
    // إدارة البلوكات
    'blocks_description': 'إدارة البلوكات في النظام',
    'blocks_list': 'قائمة البلوكات',
    'add_block': 'إضافة بلوك',
    'edit_block': 'تعديل البلوك',
    'no_blocks_found': 'لا توجد بلوكات',
    'block_added': 'تم إضافة البلوك بنجاح',
    'block_updated': 'تم تحديث البلوك بنجاح',
    'block_deleted': 'تم حذف البلوك بنجاح',
    'error_deleting_block': 'خطأ في حذف البلوك',
    'confirm_delete_block': 'هل أنت متأكد من حذف البلوك',
    'code': 'الكود',
    'select_block_type': 'اختر نوع البلوك',
    'enter_display_order': 'أدخل ترتيب العرض',
    'residential': 'سكني',
    'commercial': 'تجاري',
    'mixed': 'مختلط',
    'office': 'مكاتب',
    'parking': 'مواقف',
    'assigned_designs': 'التصاميم المعينة',
    'towers_count': 'عدد الأبراج',
    'units_count': 'عدد الوحدات',
    'unknown': 'غير معروف',
    'active_status': 'الحالة النشطة',
    
    // إدارة التصاميم
    'designs_management': 'إدارة التصاميم',
    'designs_management_description': 'إضافة وتعديل وحذف تصاميم المشاريع',
    'add_new_design': 'إضافة تصميم جديد',
    'edit_design': 'تعديل التصميم',
    'no_designs': 'لا توجد تصاميم',
    'no_designs_description': 'لم يتم إنشاء أي تصاميم بعد. ابدأ بإضافة تصميم جديد.',
    'image_url': 'رابط الصورة',
    'category': 'الفئة',
    'please_fill_required_fields': 'يرجى ملء الحقول المطلوبة',
    'all': 'الكل',
    
    // الداشبورد والتنقل - مفاتيح إضافية
    'go_to_section': 'انتقل إلى القسم',
    'system_sections': 'أقسام النظام',
    'basic': 'أساسي',
    
    // إحصائيات إضافية
    'available_apartments': 'الشقق المتاحة',
    'total_owners': 'إجمالي الملاك',
    'total_tenants': 'إجمالي المستأجرين',
    
    // أقسام التنقل
    'basic_data_management': 'إدارة البيانات الأساسية',
    'basic_data_description': 'إدارة الدول، المدن، المناطق، والميزات الأساسية للعقارات',
    'towers_management': 'إدارة الأبراج',
    'towers_description': 'إضافة وإدارة الأبراج والبلوكات والشقق',
    'designs_nav_description': 'تصاميم الشقق مع الصور والفيديوهات والمواصفات',
    'owners_management': 'إدارة الملاك',
    'owners_description': 'معلومات وبيانات ملاك العقارات',
    'tenants_management': 'إدارة المستأجرين',
    'tenants_description': 'بيانات المستأجرين وعقود الإيجار',
    'finance_management': 'القسم المالي',
    'finance_description': 'إدارة المدفوعات والفواتير والتقارير المالية',
    'reports_statistics': 'التقارير والإحصائيات',
    'reports_description': 'تقارير مفصلة وإحصائيات شاملة',
    'system_settings': 'إعدادات النظام',
    'settings_description': 'إعدادات عامة وتخصيص النظام',
    
    // السايد بار
    'basic_data': 'البيانات الأساسية',
    'towers_nav': 'الأبراج',
    'people': 'الأشخاص',
    'owners': 'الملاك',
    'tenants': 'المستأجرين',
    'potential_clients': 'العملاء المحتملين',
    'finance': 'المالية',
    'contracts': 'العقود',
    'payments': 'المدفوعات',
    'reports': 'التقارير',
    'settings': 'الإعدادات',

    // معالج التصميم
    'design_wizard_basic_info': 'المعلومات الأساسية',
    'design_wizard_category': 'الفئة والسوق المستهدف',
    'design_wizard_rooms': 'المساحة والغرف',
    'design_wizard_pricing': 'الأسعار والتسعير',
    'design_wizard_expenses': 'المصاريف والرسوم',
    'design_wizard_features': 'الميزات والمرافق',
    'design_wizard_appliances': 'الأجهزة والأدوات',
    'design_wizard_payment_plans': 'خطط الدفع',
    'design_wizard_media': 'الصور والفيديوهات',
    'design_wizard_review': 'المراجعة النهائية',
    'wizard_next': 'التالي',
    'wizard_previous': 'السابق',
    'wizard_step': 'الخطوة',
    'wizard_of': 'من',
    'arabic_name_required': 'الاسم باللغة العربية',
    'english_name_required': 'الاسم باللغة الإنجليزية',
    'arabic_description_field': 'الوصف باللغة العربية',
    'english_description_field': 'الوصف باللغة الإنجليزية',
    'enter_arabic_name_placeholder': 'أدخل اسم التصميم بالعربية',
    'enter_english_name_placeholder': 'Enter design name in English',
    'enter_arabic_desc_placeholder': 'وصف مفصل للتصميم بالعربية',
    'enter_english_desc_placeholder': 'Detailed description in English',
    'design_category_title': 'فئة التصميم',
    'target_market_title': 'السوق المستهدف',
    'category_standard': 'عادي',
    'category_luxury': 'فاخر',
    'category_premium': 'ممتاز',
    'category_economic': 'اقتصادي',
    'category_family': 'عائلي',
    'category_executive': 'تنفيذي',
    'market_general': 'عام',
    'market_bachelors': 'عزاب',
    'market_families': 'عائلات',
    'market_executives': 'تنفيذيين',
    'market_students': 'طلاب',
    'market_seniors': 'كبار السن',
    'area_square_meters': 'المساحة بالمتر المربع',
    'enter_area_placeholder': 'أدخل المساحة',
    'bedrooms_count': 'غرف النوم',
    'bathrooms_count': 'دورات المياه',
    'living_rooms_count': 'غرف المعيشة',
    'kitchens_count': 'المطابخ',
    'balconies_count': 'الشرفات',
    'original_price': 'السعر الأصلي',
    'original_price_placeholder': 'السعر بالدرهم الاماراتي',
    'discount_percentage': 'نسبة الخصم (%)',
    'discount_placeholder': 'نسبة الخصم',
    'free_period_days': 'فترة مجانية (أيام)',
    'free_period_placeholder': 'عدد الأيام المجانية',
    'office_commission': 'عمولة المكتب',
    'office_commission_placeholder': 'عمولة المكتب',
    'price_summary': 'ملخص الأسعار',
    'original_price_label': 'السعر الأصلي:',
    'discount_label': 'الخصم',
    'final_price_label': 'السعر النهائي:',
    'sar_currency': 'درهم',
    'insurance_amount': 'مبلغ التأمين',
    'insurance_placeholder': 'مبلغ التأمين',
    'municipality_fees': 'رسوم البلدية',
    'municipality_placeholder': 'رسوم البلدية',
    'electricity_fees': 'رسوم الكهرباء',
    'electricity_placeholder': 'رسوم الكهرباء',
    'pro_fees': 'رسوم الاحترافية',
    'pro_fees_placeholder': 'رسوم الاحترافية',
    'maintenance_amount': 'مبلغ الصيانة',
    'maintenance_placeholder': 'مبلغ الصيانة',
    'additional_expenses': 'مبلغ مصاريف إضافية',
    'additional_expenses_placeholder': 'مبلغ المصاريف الإضافية',
    'additional_expenses_desc': 'وصف المصاريف الإضافية',
    'additional_expenses_desc_placeholder': 'وصف المصاريف الإضافية إن وجدت',
    'maintenance_type': 'نوع الصيانة',
    'gas_type': 'نوع الغاز',
    // Old maintenance types (keep for backward compatibility)
    'maintenance_comprehensive': 'صيانة شاملة',
    'maintenance_periodic': 'صيانة دورية',
    'maintenance_emergency': 'صيانة طارئة',
    'maintenance_basic': 'صيانة أساسية',
    'maintenance_none': 'بدون صيانة',
    'maintenance_advanced': 'صيانة متقدمة',
    // Correct maintenance types matching backend enums
    'maintenance_annual': 'صيانة سنوية',
    'maintenance_not_included': 'غير مشمول',
    'maintenance_optional': 'اختياري',
    'maintenance_free': 'مجاني',
    // Old gas types (keep for backward compatibility)
    'gas_natural': 'غاز طبيعي',
    'gas_lpg': 'غاز البترول المسال',
    'gas_cooking': 'غاز الطهي',
    'gas_heating': 'غاز التدفئة',
    'gas_none': 'بدون غاز',
    // Correct gas types matching backend enums
    'gas_central': 'غاز مركزي',
    'gas_cylinder': 'أسطوانات غاز',
    'expenses_summary': 'ملخص المصاريف والرسوم',
    'total_expenses': 'إجمالي المصاريف:',
    'select_features_title': 'اختيار ميزات التصميم',
    'select_features_desc': 'اختر الميزات المتوفرة في هذا التصميم',
    'no_features_available': 'لم يتم العثور على ميزات متاحة',
    'no_features_message': 'تأكد من إضافة الميزات في النظام أولاً',
    'features_selected_count': 'تم اختيار {count} ميزة',
    'features_selection_note': 'يمكنك اختيار أو إلغاء اختيار الميزات بالضغط عليها',
    'select_appliances_title': 'اختيار الأجهزة والمعدات',
    'select_appliances_desc': 'اختر الأجهزة المتوفرة وحدد الكمية المطلوبة',
    'no_appliances_available': 'لم يتم العثور على أجهزة متاحة',
    'no_appliances_message': 'تأكد من إضافة الأجهزة في النظام أولاً',
    'appliances_notes_optional': 'ملاحظات (اختياري)',
    'appliances_notes_placeholder': 'أضف ملاحظات حول هذا الجهاز...',
    'appliances_selected_count': 'تم اختيار {count} جهاز',
    'appliances_total_quantity': 'إجمالي الكمية: {total} قطعة',
    'media_title': 'الصور والفيديوهات',
    'media_description': 'ارفع صور وفيديو التصميم',
    'media_cover_image_title': 'الصورة الرئيسية للتصميم',
    'media_cover_image_description': 'ارفع الصورة الرئيسية التي ستظهر كغلاف للتصميم',
    'media_choose_cover_image': 'اختر الصورة الرئيسية',
    'media_additional_images_title': 'صور إضافية للتصميم',
    'media_additional_images_description': 'ارفع مجموعة من الصور توضح تفاصيل التصميم',
    'media_choose_multiple_images': 'اختر صور متعددة',
    'media_video_optional': 'فيديو التصميم (اختياري)',
    'media_video_description': 'ارفع فيديو يوضح التصميم والتفاصيل',
    'media_choose_video': 'اختر فيديو',
    'media_images_selected': 'تم اختيار {count} صورة',
    'media_upload_tips_title': 'نصائح لرفع الملفات:',
    'media_tip_high_quality': 'تأكد من أن الصور عالية الجودة وواضحة',
    'media_tip_image_size': 'الحد الأقصى لحجم الصورة: 5 ميجابايت',
    'media_tip_video_size': 'الحد الأقصى لحجم الفيديو: 50 ميجابايت',
    'media_tip_image_formats': 'الصيغ المدعومة للصور: JPG, PNG, WebP',
    'media_tip_video_formats': 'الصيغ المدعومة للفيديو: MP4, WebM, MOV',
    'review_title': 'مراجعة بيانات التصميم النهائية',
    'review_basic_info': 'المعلومات الأساسية',
    'review_space_rooms': 'تفاصيل المساحة والغرف',
    'review_pricing_info': 'معلومات الأسعار',
    'review_additional_info': 'معلومات إضافية',
    'review_selected_features': 'الميزات المختارة',
    'review_selected_appliances': 'الأجهزة المختارة',
    'review_uploaded_files': 'الملفات المرفقة',
    'review_not_uploaded': 'لم يتم الرفع',
    'review_no_features_selected': 'لم يتم اختيار أي ميزات',
    'review_no_appliances_selected': 'لم يتم اختيار أي أجهزة',
    
    // Payment plans
    'add_payment_plan': 'إضافة خطة دفع',
    'payment_plan_name_ar': 'اسم الخطة (عربي)',
    'payment_plan_name_en': 'اسم الخطة (إنجليزي)',
    'payment_plan_description_ar': 'وصف الخطة (عربي)',
    'payment_plan_description_en': 'وصف الخطة (إنجليزي)',
    'down_payment_percentage': 'نسبة الدفعة المقدمة (%)',
    'down_payment_months': 'أشهر الدفعة المقدمة',
    'installment_percentage': 'نسبة القسط (%)',
    'installment_months': 'أشهر التقسيط',
    'remove_payment_plan': 'حذف خطة الدفع',
    'payment_plans_help': 'يمكنك إضافة خطط دفع متعددة مثل (خطة واحدة، 3 خطط، 4 خطط، إلخ)',
    'no_payment_plans': 'لم يتم إضافة خطط دفع بعد',
    'payment_plan_name_ar_required': 'اسم الخطة باللغة العربية مطلوب',
    'payment_plan_name_en_required': 'اسم الخطة باللغة الإنجليزية مطلوب',
    'down_payment_percentage_required': 'نسبة الدفعة المقدمة مطلوبة',
    'installment_percentage_required': 'نسبة القسط مطلوبة',
    
    'review_saving': 'جاري الحفظ...',
    'review_save_changes': 'حفظ التعديلات',
    'review_create_design': 'إنشاء التصميم',
    'review_status': 'الحالة',
    'review_status_active': 'نشط',
    'review_status_inactive': 'غير نشط',
    'review_images_count': 'صور',
    'review_video': 'فيديو',
    'review_selected_payment_plans': 'خطط الدفع المختارة',
    'review_payment_plan_single': 'دفعة واحدة',
    'review_payment_plan_installments': 'دفعات',
    'review_payment_plan_per_installment': 'لكل دفعة',
    'review_payment_plan_total': 'إجمالي',
    'target_market': 'السوق المستهدف',
    'rooms_area_label': 'المساحة',
    'rooms_area_unit': 'متر مربع',
    'rooms_bedrooms': 'غرف النوم',
    'rooms_bathrooms': 'الحمامات',
    'rooms_living_rooms': 'غرف المعيشة',
    'pricing_original_rent_price': 'سعر الإيجار الأصلي',
    'pricing_currency': 'درهم',
    'pricing_discount_percentage': 'نسبة الخصم',
    'pricing_final_price': 'السعر النهائي',
    'pricing_free_period_days': 'فترة مجانية',
    'pricing_free_period_unit': 'يوم',
    'expenses_office_commission': 'عمولة المكتب',
    'expenses_maintenance_type': 'نوع الصيانة',
    'expenses_gas_type': 'نوع الغاز',
    'existing_file': 'ملف موجود',
    'existing_files': 'ملفات موجودة',
    'maintenance_not_specified': 'غير محدد',
    'gas_not_specified': 'غير محدد',
    'category_not_specified': 'غير محدد',
    'market_not_specified': 'غير محدد',
    
    // DataTable translations
    'search_placeholder': 'البحث...',
    'filter_button': 'تصفية',
    'no_data_display': 'لا توجد بيانات للعرض',
    'loading_text': 'جارٍ التحميل...',
    'actions_column': 'الإجراءات',
    'previous_page': 'السابق',
    'next_page': 'التالي',
    'page_of': 'صفحة {page} من {total}',
    'showing_entries': 'عرض {start} إلى {end} من أصل {total} عنصر',
    
    // AppliancesPage new translations
    'appliances_management': 'إدارة الأجهزة والأدوات',
    'appliances_description': 'إضافة وتعديل وحذف الأجهزة والأدوات ({count} جهاز)',
    'arabic_name_column': 'الاسم بالعربية',
    'english_name_column': 'الاسم بالإنجليزية',
    'display_order_column': 'ترتيب العرض',
    'status_column': 'الحالة',
    'no_appliances_description': 'لم يتم إنشاء أي أجهزة بعد. ابدأ بإضافة جهاز جديد.',
    'add_appliance': 'إضافة جهاز جديد',
    'add_button': 'إضافة',
    'appliance_active': 'الجهاز نشط',
    'appliance_active_description': 'هل هذا الجهاز متاح للاستخدام؟',
    
    // Design steps translations
    'step_counter': 'الخطوة {current} من {total}',
    'design_wizard_steps': 'خطوات إنشاء التصميم',
    
    // FormModal and Cities page new translations
    'saving_text': 'جارٍ الحفظ...',
    'cities_management': 'إدارة المدن',
    'cities_description': 'إضافة وتعديل وحذف المدن في النظام',
    'city_name_english': 'اسم المدينة (بالإنجليزية)',
    'city_name_arabic': 'اسم المدينة (بالعربية)',
    'country': 'الدولة',
    'choose_country': 'اختر الدولة',
    'city_active': 'المدينة نشطة',
    'cities_list': 'قائمة المدن',
    'phone_code': 'كود الرقم الدولي',
    
    // Municipality fees free period translations
    'include_municipality_free_period': 'تضمين الفترة المجانية',
    'municipality_fees_calculation': 'حساب رسوم البلدية',
    'free_period_from_pricing': 'الفترة المجانية من خطوة التسعير',
    'auto_calculated_from_pricing_step': 'يتم الحساب تلقائياً بناءً على الفترة المجانية المدخلة في خطوة التسعير',
    'with_free_period': 'مع الفترة المجانية',
    'without_free_period': 'بدون الفترة المجانية',
    'calculated_amount': 'المبلغ المحسوب',
    
  // Builder / Tower creation workflow (Arabic)
  'builder_title': 'منشئ الأبراج التفاعلي',
  'builder_subtitle': 'اتبع الخطوات لإنشاء برج جديد مع البلوكات والطوابق والشقق',
  'builder_step_completed': 'خطوة مكتملة',
  'builder_step_current': 'خطوة حالية',
  'builder_step_upcoming': 'خطوة قادمة',
  'builder_tower_created': '✓ البرج منشأ',
  'builder_blocks_created': '✓ البلوكات منشأة',
  'builder_floors_defined': '✓ تعريف الطوابق',
  'builder_floors_created': '✓ الطوابق منشأة',
  'builder_units_created': '✓ الشقق منشأة',
  'builder_reset': 'إعادة تعيين',
  'builder_reset_done': 'تم إعادة تعيين النظام',
  'builder_visual_preview': 'المعاينة المرئية',
  'builder_full_screen': 'عرض كامل',
  'builder_close_full': 'إغلاق العرض الكامل',
  'builder_drag_to_pan': 'اسحب للتنقل',
  'builder_progress_label': 'التقدم',
  'builder_current_stage': 'المرحلة الحالية',
  'builder_full_visualization_title': 'المعاينة الكاملة',
  'builder_full_visualization_desc': 'عرض تفصيلي بحجم كامل للمبنى',
  'builder_zoom_hint': 'يمكنك التكبير والتصغير باستخدام عجلة الماوس أو إيماءات اللمس',
  'builder_close_full_button': 'إغلاق العرض الكامل',
  'builder_step1_title': 'إنشاء برج جديد',
  'builder_step2_title': 'المرحلة الثانية: البلوكات وعدد الطوابق',
  'builder_step3_title': 'المرحلة 3: تعريف الطوابق',
  'builder_step4_title': 'المرحلة الرابعة: إنشاء الطوابق في قاعدة البيانات',
  'builder_step5_title': 'الخطوة 5: تعريف الشقق',
  // Step 1 keys
  'builder_step1_heading': 'إنشاء برج جديد',
  'builder_basic_info_heading': 'المعلومات الأساسية',
  'builder_location_heading': 'الموقع والعنوان',
  'builder_tower_name_ar_label': 'اسم البرج (عربي) *',
  'builder_tower_name_ar_placeholder': 'برج المملكة',
  'builder_tower_name_en_label': 'اسم البرج (إنجليزي) *',
  'builder_tower_description_ar_label': 'الوصف (عربي)',
  'builder_tower_description_ar_placeholder': 'وصف مختصر للبرج...',
  'builder_tower_description_en_label': 'الوصف (إنجليزي)',
  'builder_construction_year_label': 'سنة البناء',
  'builder_main_image_label': 'الصورة الرئيسية',
  'builder_choose_image': 'اختر صورة',
  'builder_change_image': 'تغيير الصورة',
  'builder_developer_name_label': 'اسم المطور',
  'builder_management_company_label': 'شركة الإدارة',
  'builder_address_label': 'العنوان التفصيلي',
  'builder_address_placeholder': 'شارع الملك فهد، حي العليا',
  'builder_save_and_continue': 'حفظ والمتابعة',
  'builder_recreate_tower': 'إعادة إنشاء البرج',
  'builder_saving': 'جاري الحفظ...',
  // Step 2 keys
  'builder_step2_heading': 'المرحلة الثانية: البلوكات وعدد الطوابق',
  'builder_select_blocks_label': 'اختر البلوكات من القائمة المتاحة *',
  'builder_blocks_floorcount_heading': 'تحديد عدد الطوابق لكل بلوك',
  'builder_blocks_floors_placeholder': 'عدد الطوابق',
  'builder_save_blocks_and_next': 'حفظ البلوكات والانتقال للخطوة التالية',
  // Step 3 keys
  'builder_step3_heading': 'المرحلة 3: تعريف الطوابق',
  'builder_range_from': 'من',
  'builder_range_to': 'إلى',
  'builder_range_label': 'النطاق',
  'builder_blocks_label': 'البلوكات',
  'builder_will_create_defs': 'سيتم إنشاء تعريفات لـ',
  'builder_floor_type_label': 'نوع الطابق',
  'builder_code_prefix_label': 'بادئة الكود',
  'builder_unit_type_label': 'نوع الوحدة',
  'builder_units_count_label': 'عدد الوحدات',
  'builder_units_start_number_label': 'بداية الترقيم',
  'builder_mixed_units_label': 'وحدات مختلطة / أرضي',
  'builder_no_units_label': 'لا وحدات',
  'builder_add_label': 'إضافة',
  'builder_preview_floors_label': 'طوابق للمعاينة',
  'builder_clear_preview': 'مسح',
  // Step 4 keys
  'builder_step4_heading': 'المرحلة الرابعة: إنشاء الطوابق في قاعدة البيانات',
  'builder_floors_summary_heading': 'ملخص الطوابق المعرفة:',
  'builder_total_label': 'إجمالي:',
  'builder_ready_to_create_message': '🚀 جاهز للإنشاء! سيتم إنشاء الطوابق والوحدات في قاعدة البيانات باستخدام التعريفات المفصلة من الخطوة السابقة.',
  'builder_create_floors_units': 'إنشاء الطوابق والوحدات',
  'builder_recreate_floors': 'إعادة إنشاء الطوابق',
  'builder_next_manage_units': 'التالي - إدارة الشقق',
  // Step 5 keys
  'builder_step5_heading': 'الخطوة 5: تعريف الشقق',
  'builder_guidelines_title': 'الإرشادات:',
  'builder_blocks_selection_label': 'اختيار البلوكات',
  'builder_loading_floors': 'جاري تحميل الطوابق...',
  'builder_no_blocks_available': 'لا توجد بلوكات متاحة',
  'builder_range_select_checkbox': 'اختيار شقق بالنطاق (لسهولة التعامل مع المباني الكبيرة)',
  'builder_floor_range_label': 'نطاق الطوابق',
  'builder_unit_range_label': 'نطاق أرقام الشقق',
  'builder_select_units_in_range': 'اختيار الشقق في النطاق',
  'builder_clear_selections': 'مسح الاختيارات',
  'builder_available_units_heading': 'الشقق المتاحة',
  'builder_units_selected_count': 'محددة',
  'builder_design_selection_label': 'اختيار التصميم',
  'builder_assign_design_button': 'تعيين التصميم',
  'builder_no_floors_for_block': 'لا توجد طوابق لهذا البلوك',
  // Step 3 & 5 additional localization keys (Arabic)
  'builder_step3_edit_hint': 'أي تعديل هنا لا يُفقد التعريفات السابقة غير المحفوظة ✅',
  'builder_mixed_units_hint': 'لن تُفقد هذه الوحدات عند تغيير النطاق، يتم دمجها مع التعريفات السابقة.',
  'builder_defs_will_create_count': 'سيتم إنشاء تعريفات لـ {count} طابق (غير محفوظة بعد)',
  'builder_block_label': 'بلوك',
  'builder_floor_singular': 'طابق',
  'builder_floors_suffix': 'طابق',
  'builder_units_suffix': 'شقة',
  'builder_code_label': 'الكود:',
  'builder_type_label': 'النوع:',
  'builder_units_label': 'الوحدات:',
  'builder_start_label': 'بداية:',
  'builder_mixed_units_short': 'وحدات مختلطة:',
  'builder_delete': 'حذف',
  'builder_progress_format': '{current}/{total} ({percent}%)',
  'builder_floor_mismatch_warning': 'تحذير: طوابق البلوكات المختارة غير متطابقة. يُنصح بتعريف كل بلوك لوحده أو استخدام طريقة التعريف الأخرى.',
  'builder_step5_guidelines_desc': 'اختر البلوكات التي تريد تعريف الشقق بها، ثم اختر التصميم المناسب للشقق',
  'builder_note_select_blocks_first': 'يجب اختيار البلوكات أولاً لعرض الطوابق والشقق المتاحة',
  'builder_blocks_selected_ready': 'تم اختيار {count} بلوك - الطوابق والشقق متاحة الآن',
  'builder_floors_available_count': '{count} طابق متاح',
  'builder_units_available_count': '{count} رقم شقة متاح',
  'builder_floor_from_label': 'من الطابق',
  'builder_floor_to_label': 'إلى الطابق',
  'builder_select_floor_placeholder': 'اختر الطابق',
  'builder_unit_from_label': 'من رقم الشقة',
  'builder_unit_to_label': 'إلى رقم الشقة',
  'builder_select_unit_placeholder': 'اختر رقم الشقة',
  'builder_range_select_success': 'تم اختيار {count} شقة من النطاق المحدد',
  'builder_select_units_and_design_warning': 'الرجاء اختيار الشقق والتصميم',
  'builder_assign_design_success': 'تم تعيين التصميم لـ {count} شقة بنجاح',
  'builder_assign_design_error': 'خطأ في تعيين التصميم',
  'builder_visual_selected_summary': 'الشقق المختارة بصرياً: {visual} | سيتم التعيين لـ {units} شقة',
  'builder_ready_assign_design_count': 'جاهز لتعيين التصميم لـ {count} شقة.',
  'builder_assign_design_with_count': 'تعيين التصميم ({count} شقة)',
  },
  en: {
    // Home page texts
    'dashboard': 'Dashboard',
    'welcome': 'Welcome',
    'home': 'Home',
    
    // Navigation texts
    'countries': 'Countries',
    'cities': 'Cities', 
    'areas': 'Areas',
    'features': 'Features',
    'appliances': 'Appliances & Tools',
    'blocks': 'Blocks',
    'designs': 'Designs',
    'logout': 'Logout',
    
    // Login texts
    'login': 'Login',
    'email': 'Email',
    'password': 'Password',
    'login_button': 'Login',
    'login_title': 'Sign In',
    'login_subtitle': 'Enter your credentials to access the Real Estate CRM',
    'email_placeholder': 'Enter your email',
    'password_placeholder': 'Enter your password',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot password?',
    'login_error': 'Invalid email or password',
    'hide_password': 'Hide password',
    'show_password': 'Show password',
    'no_account': "Don't have an account?",
    'sign_up': 'Sign up',
    
    // Statistics texts
    'total_countries': 'Total Countries',
    'total_cities': 'Total Cities',
    'total_areas': 'Total Areas',
    'total_towers': 'Total Towers',
    
    // Data management texts
    'manage_countries': 'Manage Countries in the System',
    'manage_cities': 'Manage Cities',
    'manage_areas': 'Manage Areas',
    'manage_features': 'Manage Tower Features',
    'manage_appliances': 'Manage Appliances & Tools',
    'add_new_country': 'Add New Country',
    'add_new_city': 'Add New City',
    'add_new_area': 'Add New Area',
    'add_new_feature': 'Add New Feature',
    'add_new_appliance': 'Add New Appliance',
    'edit_country': 'Edit Country',
    'edit_city': 'Edit City',
    'edit_area': 'Edit Area',
    'edit_feature': 'Edit Feature',
    'edit_appliance': 'Edit Appliance',
    
    // Form texts
    'arabic_name': 'Arabic Name',
    'english_name': 'English Name',
    'enter_arabic_name': 'Enter Arabic name',
    'enter_block_code': 'Enter block code',
    'enter_english_name': 'Enter English name',
    'enter_arabic_description': 'Enter Arabic description',
    'enter_english_description': 'Enter English description',
    'name': 'Name',
    'country_code': 'Country Code',
    'description_ar': 'Arabic Description',
    'description_en': 'English Description',
    'is_active': 'Active',
    'status': 'Status',
    'active': 'Active',
    'inactive': 'Inactive',
    'actions': 'Actions',
    'description': 'Description',
    
    // Confirmation texts
    'confirm_delete': 'Confirm Delete',
    'confirm_delete_country': 'Are you sure you want to delete this country? All associated cities and areas will be deleted.',
    'confirm_delete_city': 'Are you sure you want to delete this city? All associated areas will be deleted.',
    'confirm_delete_area': 'Are you sure you want to delete this area?',
    'confirm_delete_feature': 'Are you sure you want to delete this feature?',
    'confirm_delete_appliance': 'Are you sure you want to delete this appliance?',
    
    // Success messages
    'country_added': 'Country added successfully',
    'country_updated': 'Country updated successfully',
    'country_deleted': 'Country deleted successfully',
    'city_added': 'City added successfully',
    'city_updated': 'City updated successfully',
    'city_deleted': 'City deleted successfully',
    'area_added': 'Area added successfully',
    'area_updated': 'Area updated successfully',
    'area_deleted': 'Area deleted successfully',
    'feature_added': 'Feature added successfully',
    'feature_updated': 'Feature updated successfully',
    'feature_deleted': 'Feature deleted successfully',
    'appliance_added': 'Appliance added successfully',
    'appliance_updated': 'Appliance updated successfully',
    'appliance_deleted': 'Appliance deleted successfully',
    
    // Blocks management
    'blocks_description': 'Manage blocks in the system',
    'blocks_list': 'Blocks List',
    'add_block': 'Add Block',
    'edit_block': 'Edit Block',
    'no_blocks_found': 'No blocks found',
    'block_added': 'Block added successfully',
    'block_updated': 'Block updated successfully',
    'block_deleted': 'Block deleted successfully',
    'error_deleting_block': 'Error deleting block',
    'confirm_delete_block': 'Are you sure you want to delete the block',
    'code': 'Code',
    'select_block_type': 'Select block type',
    'enter_display_order': 'Enter display order',
    'residential': 'Residential',
    'commercial': 'Commercial',
    'mixed': 'Mixed',
    'office': 'Office',
    'parking': 'Parking',
    'assigned_designs': 'Assigned Designs',
    'towers_count': 'Towers Count',
    'units_count': 'Units Count',
    'unknown': 'Unknown',
    'active_status': 'Active Status',
    
    // General texts
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'cancel': 'Cancel',
    'save': 'Save',
    'save_changes': 'Save Changes',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'search': 'Search',
    'close': 'Close',
    'confirm': 'Confirm',
    'yes': 'Yes',
    'no': 'No',
    'back': 'Back',
  'warning': 'Warning',
  'note': 'Note',
    'select_city': 'Select a city to view areas',
    'click_city': 'Click on any city above to view available areas',
    
    // System messages
    'no_data': 'No data available',
    'no_areas_in_city': 'No areas in this city',
    'no_features': 'No features available',
    'no_appliances': 'No appliances available',
    'network_error': 'Network error',
    'server_error': 'Server error',
    'unauthorized': 'Unauthorized',
    'forbidden': 'Forbidden',
    'not_found': 'Not found',
    'delete_not_supported': 'Delete operation not currently supported',
    'delete_error': 'Unable to delete',
    
    // Features management - additional keys
    'features_management': 'Features Management',
    'features_management_description': 'Add, edit and delete tower features',
    'delete_feature_confirmation': 'Are you sure you want to delete this feature?',
    'no_features_description': 'No features have been created yet. Start by adding a new feature.',
    'loading_features': 'Loading features...',
    'feature_active': 'Feature Active',
    'feature_active_description': 'Is this feature available for use?',
    'display_order': 'Display Order',
    'english_description': 'English Description',
    'arabic_description': 'Arabic Description',
    
    // Unit Designs management
    'unitDesigns': 'Unit Designs',
    'manageUnitDesigns': 'Manage unit designs with full CRUD operations and copy functionality',
    'addNew': 'Add New',
    'searchDesigns': 'Search designs...',
    'allCategories': 'All Categories',
    'standard': 'Standard',
    'luxury': 'Luxury',
    'premium': 'Premium',
    'economic': 'Economic',
    'totalDesigns': 'Total Designs',
    'sqm': 'sqm',
    'copy': 'Copy',
    'designCategory': 'Design Category',
    'area': 'Area',
    'price': 'Price',
    'noDesigns': 'No Unit Designs',
    'noDesignsMessage': 'Get started by creating a new unit design.',
    'createFirstDesign': 'Create First Design',
    'addNewDesign': 'Add New Design',
    'arabicName': 'Arabic Name',
    'englishName': 'English Name',
    'arabicDescription': 'Arabic Description',
    'englishDescription': 'English Description',
    'pricePerMeter': 'Price Per Meter',
    'targetMarket': 'Target Market',
    'images': 'Images',
    'videos': 'Videos',
    'editDesign': 'Edit Design',
    'copyDesign': 'Copy Design',
    'deleteDesign': 'Delete Design',
    'deleteDesignConfirm': 'Are you sure you want to delete this design? This action cannot be undone.',
    'errorLoadingData': 'Error loading data',
    
    // Designs management
    'designs_management': 'Designs Management',
    'designs_management_description': 'Add, edit and delete project designs',
    'add_new_design': 'Add New Design',
    'edit_design': 'Edit Design',
    'no_designs': 'No designs available',
    'no_designs_description': 'No designs have been created yet. Start by adding a new design.',
    'image_url': 'Image URL',
    'category': 'Category',
    'please_fill_required_fields': 'Please fill in required fields',
    'all': 'All',
    
    // Dashboard and navigation - additional keys
    'go_to_section': 'Go to Section',
    'system_sections': 'System Sections',
    'basic': 'Basic',
    
    // Additional statistics
    'available_apartments': 'Available Apartments',
    'total_owners': 'Total Owners',
    'total_tenants': 'Total Tenants',
    
    // Navigation sections
    'basic_data_management': 'Basic Data Management',
    'basic_data_description': 'Manage countries, cities, areas, and basic property features',
    'towers_management': 'Towers Management',
    'towers_description': 'Add and manage towers, blocks and apartments',
    'designs_nav_description': 'Apartment designs with images, videos and specifications',
    'owners_management': 'Owners Management',
    'owners_description': 'Property owners information and data',
    'tenants_management': 'Tenants Management',
    'tenants_description': 'Tenant data and rental contracts',
    'finance_management': 'Finance Management',
    'finance_description': 'Manage payments, invoices and financial reports',
    'reports_statistics': 'Reports & Statistics',
    'reports_description': 'Detailed reports and comprehensive statistics',
    'system_settings': 'System Settings',
    'settings_description': 'General settings and system customization',
    
    // Sidebar
    'basic_data': 'Basic Data',
    'towers_nav': 'Towers',
    'people': 'People',
    'owners': 'Owners',
    'tenants': 'Tenants',
    'potential_clients': 'Potential Clients',
    'finance': 'Finance',
    'contracts': 'Contracts',
    'payments': 'Payments',
    'reports': 'Reports',
    'settings': 'Settings',

    // Design Wizard
    'design_wizard_basic_info': 'Basic Information',
    'design_wizard_category': 'Category & Target Market',
    'design_wizard_rooms': 'Area & Rooms',
    'design_wizard_pricing': 'Pricing & Costs',
    'design_wizard_expenses': 'Expenses & Fees',
    'design_wizard_features': 'Features & Amenities',
    'design_wizard_appliances': 'Appliances & Equipment',
    'design_wizard_payment_plans': 'Payment Plans',
    'design_wizard_media': 'Images & Videos',
    'design_wizard_review': 'Final Review',
    'wizard_next': 'Next',
    'wizard_previous': 'Previous',
    'wizard_step': 'Step',
    'wizard_of': 'of',
    'arabic_name_required': 'Arabic Name',
    'english_name_required': 'English Name',
    'arabic_description_field': 'Arabic Description',
    'english_description_field': 'English Description',
    'enter_arabic_name_placeholder': 'Enter design name in Arabic',
    'enter_english_name_placeholder': 'Enter design name in English',
    'enter_arabic_desc_placeholder': 'Detailed description in Arabic',
    'enter_english_desc_placeholder': 'Detailed description in English',
    'design_category_title': 'Design Category',
    'target_market_title': 'Target Market',
    'category_standard': 'Standard',
    'category_luxury': 'Luxury',
    'category_premium': 'Premium',
    'category_economic': 'Economic',
    'category_family': 'Family',
    'category_executive': 'Executive',
    'market_general': 'General',
    'market_bachelors': 'Bachelors',
    'market_families': 'Families',
    'market_executives': 'Executives',
    'market_students': 'Students',
    'market_seniors': 'Seniors',
    'area_square_meters': 'Area in Square Meters',
    'enter_area_placeholder': 'Enter area',
    'bedrooms_count': 'Bedrooms',
    'bathrooms_count': 'Bathrooms',
    'living_rooms_count': 'Living Rooms',
    'kitchens_count': 'Kitchens',
    'balconies_count': 'Balconies',
    'original_price': 'Original Price',
    'original_price_placeholder': 'Price in Saudi Riyal',
    'discount_percentage': 'Discount Percentage (%)',
    'discount_placeholder': 'Discount percentage',
    'free_period_days': 'Free Period (Days)',
    'free_period_placeholder': 'Number of free days',
    'office_commission': 'Office Commission',
    'office_commission_placeholder': 'Office commission',
    'price_summary': 'Price Summary',
    'original_price_label': 'Original Price:',
    'discount_label': 'Discount',
    'final_price_label': 'Final Price:',
    'sar_currency': 'SAR',
    'insurance_amount': 'Insurance Amount',
    'insurance_placeholder': 'Insurance amount',
    'municipality_fees': 'Municipality Fees',
    'municipality_placeholder': 'Municipality fees',
    'electricity_fees': 'Electricity Fees',
    'electricity_placeholder': 'Electricity fees',
    'pro_fees': 'Professional Fees',
    'pro_fees_placeholder': 'Professional fees',
    'maintenance_amount': 'Maintenance Amount',
    'maintenance_placeholder': 'Maintenance amount',
    'additional_expenses': 'Additional Expenses Amount',
    'additional_expenses_placeholder': 'Additional expenses amount',
    'additional_expenses_desc': 'Additional Expenses Description',
    'additional_expenses_desc_placeholder': 'Describe additional expenses if any',
    'maintenance_type': 'Maintenance Type',
    'gas_type': 'Gas Type',
    // Old maintenance types (keep for backward compatibility)
    'maintenance_comprehensive': 'Comprehensive Maintenance',
    'maintenance_periodic': 'Periodic Maintenance',
    'maintenance_emergency': 'Emergency Maintenance',
    'maintenance_basic': 'Basic Maintenance',
    'maintenance_none': 'No Maintenance',
    'maintenance_advanced': 'Advanced Maintenance',
    // Correct maintenance types matching backend enums
    'maintenance_annual': 'Annual',
    'maintenance_not_included': 'Not Included',
    'maintenance_optional': 'Optional',
    'maintenance_free': 'Free',
    // Old gas types (keep for backward compatibility)
    'gas_natural': 'Natural Gas',
    'gas_lpg': 'LPG',
    'gas_cooking': 'Cooking Gas',
    'gas_heating': 'Heating Gas',
    'gas_none': 'No Gas',
    // Correct gas types matching backend enums
    'gas_central': 'Central Gas',
    'gas_cylinder': 'Gas Cylinder',
    'expenses_summary': 'Expenses & Fees Summary',
    'total_expenses': 'Total Expenses:',
    'select_features_title': 'Select Design Features',
    'select_features_desc': 'Choose available features for this design',
    'no_features_available': 'No features available',
    'no_features_message': 'Make sure to add features to the system first',
    'features_selected_count': '{count} features selected',
    'features_selection_note': 'You can select or deselect features by clicking on them',
    'select_appliances_title': 'Select Appliances & Equipment',
    'select_appliances_desc': 'Choose available appliances and specify required quantity',
    'no_appliances_available': 'No appliances available',
    'no_appliances_message': 'Make sure to add appliances to the system first',
    'appliances_notes_optional': 'Notes (Optional)',
    'appliances_notes_placeholder': 'Add notes about this appliance...',
    'appliances_selected_count': '{count} appliances selected',
    'appliances_total_quantity': 'Total quantity: {count} pieces',
    'media_title': 'Images & Videos',
    'media_desc': 'Upload design images and video',
    'cover_image_title': 'Main Design Image',
    'cover_image_desc': 'Upload the main image that will appear as the design cover',
    'choose_cover_image': 'Choose Cover Image',
    'additional_images_title': 'Additional Design Images',
    'additional_images_desc': 'Upload a set of images showing design details',
    'choose_multiple_images': 'Choose Multiple Images',
    'video_title': 'Design Video (Optional)',
    'video_desc': 'Upload a video showing the design and details',
    'choose_video': 'Choose Video',
    'images_selected': '{count} images selected',
    'file_upload_tips': '💡 File Upload Tips:',
    'tip_high_quality': '• Make sure images are high quality and clear',
    'tip_image_size': '• Maximum image size: 5 MB',
    'tip_video_size': '• Maximum video size: 50 MB',
    'tip_image_formats': '• Supported image formats: JPG, PNG, WebP',
    'tip_video_formats': '• Supported video formats: MP4, WebM, MOV',
    'review_title': 'Final Design Data Review',
    'review_basic_info': 'Basic Information',
    'review_space_rooms': 'Area & Rooms Details',
    'review_pricing_info': 'Pricing Information',
    'review_additional_info': 'Additional Information',
    'review_selected_features': 'Selected Features',
    'review_selected_appliances': 'Selected Appliances',
    'review_attached_files': 'Attached Files',
    'review_cover_image': 'Cover Image:',
    'review_additional_images': 'Additional Images:',
    'review_video': 'Video:',
    'review_not_uploaded': 'Not uploaded',
    'review_no_features': 'No features selected',
    'review_no_appliances': 'No appliances selected',
    // Missing media and review translations
    'media_description': 'Upload design images and videos',
    'media_cover_image_title': 'Design Cover Image',
    'media_cover_image_description': 'Upload the main image that will appear as the design cover',
    'media_choose_cover_image': 'Choose Cover Image',
    'media_additional_images_title': 'Additional Design Images',
    'media_additional_images_description': 'Upload a collection of images showing design details',
    'media_choose_multiple_images': 'Choose Multiple Images',
    'media_video_optional': 'Design Video (Optional)',
    'media_video_description': 'Upload a video showing the design and details',
    'media_choose_video': 'Choose Video',
    'media_images_selected': '{count} images selected',
    'media_upload_tips_title': 'File Upload Tips:',
    'media_tip_high_quality': 'Ensure images are high quality and clear',
    'media_tip_image_size': 'Maximum image size: 5 MB',
    'media_tip_video_size': 'Maximum video size: 50 MB',
    'media_tip_image_formats': 'Supported image formats: JPG, PNG, WebP',
    'media_tip_video_formats': 'Supported video formats: MP4, WebM, MOV',
    'review_uploaded_files': 'Uploaded Files',
    'review_no_features_selected': 'No features selected',
    'review_no_appliances_selected': 'No appliances selected',
    
    // Payment plans
    'add_payment_plan': 'Add Payment Plan',
    'payment_plan_name_ar': 'Plan Name (Arabic)',
    'payment_plan_name_en': 'Plan Name (English)',
    'payment_plan_description_ar': 'Plan Description (Arabic)',
    'payment_plan_description_en': 'Plan Description (English)',
    'down_payment_percentage': 'Down Payment Percentage (%)',
    'down_payment_months': 'Down Payment Months',
    'installment_percentage': 'Installment Percentage (%)',
    'installment_months': 'Installment Months',
    'remove_payment_plan': 'Remove Payment Plan',
    'payment_plans_help': 'You can add multiple payment plans (1 plan, 3 plans, 4 plans, etc.)',
    'no_payment_plans': 'No payment plans added yet',
    'payment_plan_name_ar_required': 'Arabic plan name is required',
    'payment_plan_name_en_required': 'English plan name is required',
    'down_payment_percentage_required': 'Down payment percentage is required',
    'installment_percentage_required': 'Installment percentage is required',
    
    'review_saving': 'Saving...',
    'review_save_changes': 'Save Changes',
    'review_create_design': 'Create Design',
    'review_status': 'Status',
    'review_status_active': 'Active',
    'review_status_inactive': 'Inactive',
    'review_images_count': 'images',
    'review_selected_payment_plans': 'Selected Payment Plans',
    'review_payment_plan_single': 'Single Payment',
    'review_payment_plan_installments': 'Installments',
    'review_payment_plan_per_installment': 'per installment',
    'review_payment_plan_total': 'total',
    'target_market': 'Target Market',
    'rooms_area_label': 'Area',
    'rooms_area_unit': 'sqm',
    'rooms_bedrooms': 'Bedrooms',
    'rooms_bathrooms': 'Bathrooms',
    'rooms_living_rooms': 'Living Rooms',
    'pricing_original_rent_price': 'Original Rent Price',
    'pricing_currency': 'AED',
    'pricing_discount_percentage': 'Discount Percentage',
    'pricing_final_price': 'Final Price',
    'pricing_free_period_days': 'Free Period',
    'pricing_free_period_unit': 'days',
    'expenses_office_commission': 'Office Commission',
    'expenses_maintenance_type': 'Maintenance Type',
    'expenses_gas_type': 'Gas Type',
    'existing_file': 'Existing File',
    'existing_files': 'Existing Files',
    'maintenance_not_specified': 'Not specified',
    'gas_not_specified': 'Not specified',
    'category_not_specified': 'Not specified',
    'market_not_specified': 'Not specified',
    
    // DataTable translations
    'search_placeholder': 'Search...',
    'filter_button': 'Filter',
    'no_data_display': 'No data to display',
    'loading_text': 'Loading...',
    'actions_column': 'Actions',
    'previous_page': 'Previous',
    'next_page': 'Next',
    'page_of': 'Page {page} of {total}',
    'showing_entries': 'Showing {start} to {end} of {total} entries',
    
    // AppliancesPage new translations
    'appliances_management': 'Appliances Management',
    'appliances_description': 'Add, edit and delete appliances ({count} appliances)',
    'arabic_name_column': 'Arabic Name',
    'english_name_column': 'English Name',
    'display_order_column': 'Display Order',
    'status_column': 'Status',
    'no_appliances_description': 'No appliances have been created yet. Start by adding a new appliance.',
    'add_appliance': 'Add New Appliance',
    'add_button': 'Add',
    'appliance_active': 'Appliance Active',
    'appliance_active_description': 'Is this appliance available for use?',
    
    // Design steps translations
    'step_counter': 'Step {current} of {total}',
    'design_wizard_steps': 'Design Creation Steps',
    
    // FormModal and Cities page new translations
    'saving_text': 'Saving...',
    'cities_management': 'Cities Management',
    'cities_description': 'Add, edit and delete cities in the system',
    'city_name_english': 'City Name (English)',
    'city_name_arabic': 'City Name (Arabic)',
    'country': 'Country',
    'choose_country': 'Choose Country',
    'city_active': 'City Active',
    'cities_list': 'Cities List',
    'phone_code': 'Phone Code',
    
    // Municipality fees free period translations
    'include_municipality_free_period': 'Include Free Period',
    'municipality_fees_calculation': 'Municipality Fees Calculation',
    'free_period_from_pricing': 'Free Period from Pricing Step',
    'auto_calculated_from_pricing_step': 'Automatically calculated based on free period entered in pricing step',
    'with_free_period': 'With Free Period',
    'without_free_period': 'Without Free Period',
    'calculated_amount': 'Calculated Amount',
    
  // Builder / Tower creation workflow (English)
  'builder_title': 'Interactive Building Builder',
  'builder_subtitle': 'Follow the steps to create a new tower with blocks, floors and units',
  'builder_step_completed': 'Completed Step',
  'builder_step_current': 'Current Step',
  'builder_step_upcoming': 'Upcoming Step',
  'builder_tower_created': '✓ Tower Created',
  'builder_blocks_created': '✓ Blocks Created',
  'builder_floors_defined': '✓ Floors Defined',
  'builder_floors_created': '✓ Floors Created',
  'builder_units_created': '✓ Units Created',
  'builder_reset': 'Reset',
  'builder_reset_done': 'System reset',
  'builder_visual_preview': 'Visual Preview',
  'builder_full_screen': 'Full Screen',
  'builder_close_full': 'Close Full View',
  'builder_drag_to_pan': 'Drag to pan',
  'builder_progress_label': 'Progress',
  'builder_current_stage': 'Current Stage',
  'builder_full_visualization_title': 'Full Visualization',
  'builder_full_visualization_desc': 'Full-size detailed view of the building',
  'builder_zoom_hint': 'You can zoom in/out using the mouse wheel or touch gestures',
  'builder_close_full_button': 'Close Full View',
  'builder_step1_title': 'Create New Tower',
  'builder_step2_title': 'Step 2: Blocks & Floors Count',
  'builder_step3_title': 'Step 3: Floor Definitions',
  'builder_step4_title': 'Step 4: Create Floors in Database',
  'builder_step5_title': 'Step 5: Units Definition',
  // Step 1 keys
  'builder_step1_heading': 'Create New Tower',
  'builder_basic_info_heading': 'Basic Information',
  'builder_location_heading': 'Location & Address',
  'builder_tower_name_ar_label': 'Tower Name (Arabic) *',
  'builder_tower_name_ar_placeholder': 'Kingdom Tower (Arabic)',
  'builder_tower_name_en_label': 'Tower Name (English) *',
  'builder_tower_description_ar_label': 'Description (Arabic)',
  'builder_tower_description_ar_placeholder': 'Brief description of the tower...',
  'builder_tower_description_en_label': 'Description (English)',
  'builder_construction_year_label': 'Construction Year',
  'builder_main_image_label': 'Main Image',
  'builder_choose_image': 'Choose Image',
  'builder_change_image': 'Change Image',
  'builder_developer_name_label': 'Developer Name',
  'builder_management_company_label': 'Management Company',
  'builder_address_label': 'Detailed Address',
  'builder_address_placeholder': 'King Fahd Rd, Al Olaya District',
  'builder_save_and_continue': 'Save & Continue',
  'builder_recreate_tower': 'Recreate Tower',
  'builder_saving': 'Saving...',
  // Step 2 keys
  'builder_step2_heading': 'Step 2: Blocks & Floors Count',
  'builder_select_blocks_label': 'Select blocks from the available list *',
  'builder_blocks_floorcount_heading': 'Specify floor count per block',
  'builder_blocks_floors_placeholder': 'Floors count',
  'builder_save_blocks_and_next': 'Save blocks & proceed',
  // Step 3 keys
  'builder_step3_heading': 'Step 3: Floor Definitions',
  'builder_range_from': 'From',
  'builder_range_to': 'To',
  'builder_range_label': 'Range',
  'builder_blocks_label': 'Blocks',
  'builder_will_create_defs': 'Definitions to be created for',
  'builder_floor_type_label': 'Floor Type',
  'builder_code_prefix_label': 'Code Prefix',
  'builder_unit_type_label': 'Unit Type',
  'builder_units_count_label': 'Units Count',
  'builder_units_start_number_label': 'Start Number',
  'builder_mixed_units_label': 'Mixed / Ground Units',
  'builder_no_units_label': 'No units',
  'builder_add_label': 'Add',
  'builder_preview_floors_label': 'Preview Floors',
  'builder_clear_preview': 'Clear',
  // Step 4 keys
  'builder_step4_heading': 'Step 4: Create Floors in Database',
  'builder_floors_summary_heading': 'Defined Floors Summary:',
  'builder_total_label': 'Total:',
  'builder_ready_to_create_message': '🚀 Ready! Floors & units will be created in the database using the definitions from the previous step.',
  'builder_create_floors_units': 'Create Floors & Units',
  'builder_recreate_floors': 'Recreate Floors',
  'builder_next_manage_units': 'Next - Manage Units',
  // Step 5 keys
  'builder_step5_heading': 'Step 5: Units Definition',
  'builder_guidelines_title': 'Guidelines:',
  'builder_blocks_selection_label': 'Select Blocks',
  'builder_loading_floors': 'Loading floors...',
  'builder_no_blocks_available': 'No blocks available',
  'builder_range_select_checkbox': 'Select units by range (for large buildings)',
  'builder_floor_range_label': 'Floor Range',
  'builder_unit_range_label': 'Unit Numbers Range',
  'builder_select_units_in_range': 'Select Units in Range',
  'builder_clear_selections': 'Clear Selections',
  'builder_available_units_heading': 'Available Units',
  'builder_units_selected_count': 'selected',
  'builder_design_selection_label': 'Design Selection',
  'builder_assign_design_button': 'Assign Design',
  'builder_no_floors_for_block': 'No floors for this block',
  // Step 3 & 5 additional localization keys (English)
  'builder_step3_edit_hint': 'Any change here will not discard previous unsaved definitions ✅',
  'builder_mixed_units_hint': 'These mixed units are preserved when changing range; they merge with previous definitions.',
  'builder_defs_will_create_count': 'Will create definitions for {count} floor(s) (not saved yet)',
  'builder_block_label': 'Block',
  'builder_floor_singular': 'Floor',
  'builder_floors_suffix': 'floor',
  'builder_units_suffix': 'unit',
  'builder_code_label': 'Code:',
  'builder_type_label': 'Type:',
  'builder_units_label': 'Units:',
  'builder_start_label': 'Start:',
  'builder_mixed_units_short': 'Mixed Units:',
  'builder_delete': 'Delete',
  'builder_progress_format': '{current}/{total} ({percent}%)',
  'builder_floor_mismatch_warning': 'Warning: Selected blocks have non-matching floors. Consider defining each block separately or using an alternative method.',
  'builder_step5_guidelines_desc': 'Select the blocks you want to define units for, then choose the appropriate unit design.',
  'builder_note_select_blocks_first': 'You must select blocks first to display available floors and units',
  'builder_blocks_selected_ready': '{count} block(s) selected - floors & units are now available',
  'builder_floors_available_count': '{count} floor(s) available',
  'builder_units_available_count': '{count} unit number(s) available',
  'builder_floor_from_label': 'From floor',
  'builder_floor_to_label': 'To floor',
  'builder_select_floor_placeholder': 'Select floor',
  'builder_unit_from_label': 'From unit number',
  'builder_unit_to_label': 'To unit number',
  'builder_select_unit_placeholder': 'Select unit number',
  'builder_range_select_success': '{count} units selected from the specified range',
  'builder_select_units_and_design_warning': 'Please select units and a design',
  'builder_assign_design_success': 'Design assigned to {count} unit(s) successfully',
  'builder_assign_design_error': 'Error assigning design',
  'builder_visual_selected_summary': 'Visually selected: {visual} | Will assign to {units} units',
  'builder_ready_assign_design_count': 'Ready to assign design to {count} units.',
  'builder_assign_design_with_count': 'Assign Design ({count} units)',
  }
};

// مزود سياق اللغة
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ar');

  // تحميل اللغة المحفوظة من localStorage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['ar', 'en'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // تحديث اتجاه النص عند تغيير اللغة
  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  // دالة تغيير اللغة
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  // دالة تبديل اللغة
  const toggleLanguage = () => {
    const newLang = language === 'ar' ? 'en' : 'ar';
    setLanguage(newLang);
  };

  // دالة الترجمة
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value: LanguageContextType = {
    language,
    isRTL: language === 'ar',
    toggleLanguage,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}